### ISSUE TITLE
Increase the GPU cap in handheld mode

### ISSUE THREAD

**Issue by cucholix** [retronx-team/sys-clk#10]
Basically be able to set the GPU speed beyond 460mhz in handheld mode, it helps in games like Hellblade where the visual quality drops significantly.

**Comment by ZachyCatGames** [comment]
There’s a reason 460mhz is the max :P. Anything beyond 460mhz in handheld can cause hardware damage

**Comment by cucholix** [comment]
Wasn’t it to avoid battery strain?

**Comment by ZachyCatGames** [comment]
> Wasn’t it to avoid battery strain?

Yea.

**Comment by p-sam** [comment]
It's only made to go beyond 460Mhz with a charger on handheld

**Comment by Clydefrosch22** [comment]
can't this be like an advanced continue at your own risk thing?

i mean, i've used handheld gpu overclock with freebird until i updated to 8.1 without issues and i get protecting the end user, but leaving the option would be nice

**Comment by m4xw** [comment]
You have the option to change thee code.

**Comment by Clydefrosch22** [comment]
I think we both know that whenever people ask for something on here, while this is technically true, they rarely -actually- have that option. Not to mention I actually did try to look at the code knowing I have no idea what most of it means, just on the off-chance it could be done by changing like one obvious variable. Which maybe it could, but I couldn't tell. 
And to be honest, if I actually knew what I was doing here, I'd probably put it towards fixing Freebird, since that's overall more convenient to use in my opinion.

Don't get me wrong, I very much understand that I'm the begger here, I do. I never expect  anything to be done for me while more pressing things are around. And knowing your threads on various websites, I'm also aware of the endless floods of repetitive, explained in OP questions and often unreasonable demands, you have all the right to be snarky with people.

Still there's probably more reasons to soften handheld capping eventually, than reasons against it.

**Comment by m4xw** [comment]
We made the decision against it.
Feel free to fork.

**Comment by SaulGoodman1337** [comment]
uses my build. Cap removed.
in conjunction with ReverseNX (-RT) you could enjoy e.g. Mortal Kombat 11 without having to accept the crappy handheld graphics.

Please make sure to create a more aggressive fan curve.  This is really important because this mod already demands a lot from the handheld.

As an example you can take the curve here:
[tc]
tskin_rate_table_handheld = str!"[[-1000000, 35000, 0, 0], [35000, 43000, 50, 170], [43000, 47000, 171, 183], [47000, 50000, 183, 230], [50000, 1000000, 255, 255]]"

I am still playing around a bit at the moment. But I haven't gone above 43°c yet, which is perfectly acceptable. 

Here is the link to the build:
https://mega.nz/file/lwhgADgZ#nMDK7dFGCGSzMffF5G6FZc97Ow3SJ2t1ixKpA1-U-hk

only two lines were changed.

and to the sys-clk creators:
We are not little children who want to be patronized. Decisions we can and should want to make alone.
