### ISSUE TITLE
time:s session exhaustion

### ISSUE THREAD

**Issue by 3096** [retronx-team/sys-clk#25]
Even after calling timeExit, it seems the session is held onto as long as the process is alive. Not sure if this is intended behavior or what causes it, but I suggest consider using time:u which has more sessions.

The issue was also discussed here:
https://github.com/retronx-team/sys-clk/commit/7c7015277bd04d234d33d3b7acae4932776cf327

I was told to create an issue.

**Comment by p-sam** [comment]
> it seems the session is held onto as long as the process is alive

It's not, it's released after calling timeExit (1 session free before, 2 sessions free after)

>  I suggest consider using time:u which has more sessions.

That's not a reason per se, since that's the remaining free sessions that counts. And the first thing you said was true, we would have a problem with app and homebrew running, leaving the remaining time:u sessions to be fewer than time:s

**Comment by 3096** [comment]
I was wrong on the session thing. But time:u still has more free sessions than time:s (4, as opposed to 2 in my system).

The issue I had with timeInit failing was actually "0x64274 Memory allocation failure"
