### ISSUE TITLE
Increase GPU cap in portable mode on Mariko consoles

### ISSUE THREAD

**Issue by zal16** [retronx-team/sys-clk#31]
we know that these protections placed by the sysclk developer, are to limit the stress of the battery circuits.

but what about the Mariko consoles? They by nature consume almost half of the Erista and heat less. Would it be possible to increase the clock margin?

**Comment by zal16** [comment]
Also it's possible to go beyond 921MHz on  official charger/docked mode?

**Comment by p-sam** [comment]
Mariko doesn't go beyond 921Mhz.

As for increasing the cap, I have yet to see any power draw log from a mariko device, it would be a first step needed towards further analysis. But from what I heard (and it's not just about mariko) it looks pretty grim, and we actually thought about lowering the limit value instead of upping it

**Comment by zal16** [comment]
how can make this increase myself?

**Comment by zal16** [comment]
How to compile your source?

**Comment by m4xw** [comment]
You want to play with fire but you can't hold the stick lol

**Comment by zal16** [comment]
i installed git for windows, but i get the error: build.sh: line 19: make: command not found

**Comment by Masamune3210** [comment]
If that error doesn't make sense to you, you are really out of your environment on this one and should prob just wait for someone else. Either that or get ready to google
