### ISSUE TITLE
Power Delivery Charger isn't detected like "Original", can't go over 768 in GPU

### ISSUE THREAD

**Issue by ygordreyer** [retronx-team/sys-clk#35]
Hey guys, how is it going?

I've bought power delivery  charger, because I needed a bigger cable, but now I can't go over 768hz because sys-clk just detects as "USB charging". How can I fix this? My charger is way more powerful than the original one, so the battery it's always on 100%, and I use external cooling system, so it doesn't get that hot.

**Comment by p-sam** [comment]
You'll need another charger, finding one that is not the exact one sold by Nintendo requires testing, to find one that would deliver the correct asked profiles. I suggest that for that kind of discussion, you reach to our community via Discord, since it's not an issue, sys-clk doesn't mean to control what charger does or doesn't get detected as "Official".

Discord: https://discord.gg/nGuXmhYf

**Comment by ygordreyer** [comment]
Okay, thanks for the help! And thanks for the awesome module!
