### ISSUE TITLE
Add toolbox.json file to release

### ISSUE THREAD

**Issue by impeeza** [retronx-team/sys-clk#48]
Hi, first at all, thanks a lot for all your work.

will be nice if you include a file called toolbox.json on the release file it will be located on

\atmosphere\contents\00FF0000636C6BFF\toolbox.json

and will tell to several sysmodules managers how to enable/disable, start/stop the sysmodule, the content of file could be:

```
{
	"name"  : "sys-clk",
	"tid"   : "00FF0000636C6BFF",
	"requires_reboot": false
}
```

regards from Colombia.

**Comment by p-sam** [comment]
Thanks, we're not including a toolbox.json because there's already methods inside sys-clk to start and stop its behavior, without having to terminate the process to do so. Killing apps without giving them a chance to clean up the ressources they use is not recommended, and used to leave sys-clk in a state where you could not start it again unless the console is rebooted, since for example the service it registers would not be unregistered if killed.

**Comment by impeeza** [comment]
Hi, that's what the item "requires_reboot": true, could be used.  the sysmodules manager then, DO NOT attempt to stop the process, instead, remove the boot2.flag and the sysmodule only is unloaded until next reboot.

regards

**Comment by p-sam** [comment]
I'm aware of what "require_reboot" means and entails on Hekate Toolbox, and its ovl-sysmodule counterpart. Like I said, the fastest way to start and stop sys-clk behavior is already baked in. Repacks and such may include files alongside sys-clk, but it's outside the scope of this project
