### ISSUE TITLE
temporary overrides

### ISSUE THREAD

**Issue by eodrambo** [retronx-team/sys-clk#50]
I was looking over your readme. There's no mention of how long the temporary overrides stay in place. Whether it's until a new game or app is launched, another profile is loaded, when the system is restarted, 30 minutes, or maybe they're just system wide permanent overrides?

Could you add some clarity to your documentation?
I love your work, and if I've missed where it is already documentated, I apologize. Thanks again!

**Comment by p-sam** [comment]
Hi, temp overrides are simply never saved and stay in memory since those are temporary, in practice that means until you reboot your switch and/or you change them

I'll close this since it's not really a sys-clk issue but rather a question, it may end up being in the docs if it's ambiguous to more people
