### ISSUE TITLE
Keep same file name in releases

### ISSUE THREAD

**Issue by fennectech** [retronx-team/sys-clk#82]
I'd like if the file name in releases is kept the same.  This would result in it being much easier to use tools like aio switch updater to update sys-clk using its download custom packs feature using https://github.com/retronx-team/sys-clk/releases/download/latest/sys-clk.zip

**Comment by p-sam** [comment]
I understand the headache induced by the lack of consistency or filename pattern, but I don't intend to adhere to any for pre-release or dev builds, which happens when testing new big features, or fixes pending on new HOS versions like right now. And it's not like sys-clk is updated that frequently.

**Comment by fennectech** [comment]
could a simlink be programmatically made on build to provide the needed zip file name from github?

**Comment by CTCaer** [comment]
Don't ask absurd things.

Just use github api to get latest release asset list, like how everyone does it.
<https://api.github.com/repos/retronx-team/sys-clk/releases>
<https://api.github.com/repos/retronx-team/sys-clk/releases/125089115/assets>

You just parse the top result and you get version/date/etc and the asset link, and asset link has a singular browser_download_url for sysclk.

Hardcoding links for such is bad.
